import type {z} from 'zod';
import {getSql} from './db';
import {clubIdentity} from './identity.server';
import {readWorkingFile,writeWorkingFile,loadDeskForUser} from './pd/desk-impl.server';
import {scopeForViewer,assertAthleteAccess} from './pd/access';
import {validDate,chicagoDate,timeMinutes} from './scheduling';
import type {profileInput,availabilityInput,trackInput,metricInput,dayInput,logInput} from './coaching-contracts';
async function coach(userId:string){const me=await clubIdentity(userId);if(!['admin','coach'].includes(me.role))throw new Error('Coach access required.');const {data}=await loadDeskForUser(userId);const row=data.coaches.find(c=>c.email.toLowerCase()===me.email);if(!row)throw new Error('Coach profile is not assigned.');return {me,row};}
async function access(userId:string,athleteId:string,coached=false){const me=await clubIdentity(userId),file=await readWorkingFile();assertAthleteAccess(scopeForViewer(me,file),athleteId);if(coached&&!['admin','coach'].includes(me.role))throw new Error('Only an assigned coach can change the plan or OP level.');return me;}
function validateDay(day:string){if(!validDate(day))throw new Error('Invalid date.');}
export async function publicCoaches(){const sql=await getSql();return sql<{id:string;profile:z.infer<typeof profileInput>}>`select id,profile from coach_profiles where published=true order by profile->>'name'`;}
export async function myCoach(userId:string){const {row}=await coach(userId);const sql=await getSql();const [profile]=await sql<{profile:z.infer<typeof profileInput>}>`select profile from coach_profiles where user_id=${userId}`;const file=await readWorkingFile();return {coach:row,profile:profile?.profile,availability:file.availability.filter(a=>a.coachId===row.id)};}
export async function saveCoach(userId:string,input:z.infer<typeof profileInput>){const {row}=await coach(userId);const sql=await getSql();await sql`insert into coach_profiles(id,user_id,profile,published) values(${row.id},${userId},${JSON.stringify(input)}::jsonb,${input.published}) on conflict(user_id) do update set profile=excluded.profile,published=excluded.published,updated_at=now()`;const file=await readWorkingFile();await writeWorkingFile({...file,coaches:file.coaches.map(c=>c.id===row.id?{...c,name:input.name,specialties:input.specialties}:c)});return {ok:true};}
export async function saveAvailability(userId:string,input:z.infer<typeof availabilityInput>){const {row}=await coach(userId);for(const w of input.windows){const start=timeMinutes(w.start),end=timeMinutes(w.end),open=['Sat','Sun'].includes(w.weekday)?13*60:16*60;if(start<open||end>20*60||start>=end)throw new Error('Availability must fit the club’s reserved hours.');}const file=await readWorkingFile();await writeWorkingFile({...file,availability:[...file.availability.filter(a=>a.coachId!==row.id),...input.windows.map((w,i)=>({id:`availability:${row.id}:${i}`,coachId:row.id,weekday:w.weekday,window:`${w.start}–${w.end}`}))]});return {ok:true};}
export async function developmentProgress(userId:string,athleteId:string){await access(userId,athleteId);const sql=await getSql();const [tracks,days,logs,metrics]=await Promise.all([
 sql<{track:string;level:number;evidence:string;updated_at:Date}>`select track,level,evidence,updated_at from athlete_track_progress where athlete_id=${athleteId}`,
 sql<{day:string;focus:string;game_notes:string;items:z.infer<typeof dayInput>['items']}>`select day::text,focus,game_notes,items from athlete_training_days where athlete_id=${athleteId} and day>=${chicagoDate()}::date and day<${chicagoDate()}::date+30 order by day`,
 sql<{day:string;item_id:string;completed:boolean;reps:number;weight:number;rpe:number;notes:string}>`select day::text,item_id,completed,reps,weight,rpe,notes from athlete_training_logs where athlete_id=${athleteId} order by day desc limit 600`,
 sql<{id:string;track:string;day:string;successes:number;attempts:number;notes:string;verified:boolean}>`select id,track,day::text,successes,attempts,notes,verified from athlete_session_metrics where athlete_id=${athleteId} order by day desc limit 100`,
 ]);return {tracks,days,logs,metrics};}
export async function setTrack(userId:string,input:z.infer<typeof trackInput>){await access(userId,input.athleteId,true);const sql=await getSql();await sql`insert into athlete_track_progress(athlete_id,track,level,coach_user_id,evidence) values(${input.athleteId},${input.track},${input.level},${userId},${input.evidence}) on conflict(athlete_id,track) do update set level=excluded.level,coach_user_id=excluded.coach_user_id,evidence=excluded.evidence,updated_at=now()`;return {ok:true};}
export async function setTrainingDay(userId:string,input:z.infer<typeof dayInput>){await access(userId,input.athleteId,true);validateDay(input.day);const sql=await getSql();await sql`insert into athlete_training_days(athlete_id,day,coach_user_id,focus,game_notes,items) values(${input.athleteId},${input.day},${userId},${input.focus},${input.gameNotes},${JSON.stringify(input.items)}::jsonb) on conflict(athlete_id,day) do update set focus=excluded.focus,game_notes=excluded.game_notes,items=excluded.items,updated_at=now()`;return {ok:true};}
export async function logTraining(userId:string,input:z.infer<typeof logInput>){await access(userId,input.athleteId);validateDay(input.day);const sql=await getSql();const [plan]=await sql<{items:z.infer<typeof dayInput>['items']}>`select items from athlete_training_days where athlete_id=${input.athleteId} and day=${input.day}`;if(!plan?.items.some(i=>i.id===input.itemId))throw new Error('This drill is not on the assigned plan.');await sql`insert into athlete_training_logs(athlete_id,day,item_id,user_id,completed,reps,weight,rpe,notes) values(${input.athleteId},${input.day},${input.itemId},${userId},${input.completed},${input.reps??null},${input.weight??null},${input.rpe??null},${input.notes}) on conflict(athlete_id,day,item_id) do update set completed=excluded.completed,reps=excluded.reps,weight=excluded.weight,rpe=excluded.rpe,notes=excluded.notes,updated_at=now()`;return {ok:true};}
export async function saveMetric(userId:string,input:z.infer<typeof metricInput>){const me=await access(userId,input.athleteId);validateDay(input.day);if(input.day>chicagoDate())throw new Error('A session log cannot be dated in the future.');const sql=await getSql();await sql`insert into athlete_session_metrics(id,athlete_id,user_id,track,day,successes,attempts,notes,verified) values(${input.id},${input.athleteId},${userId},${input.track},${input.day},${input.successes},${input.attempts},${input.notes},${me.role==='coach'||me.role==='admin'}) on conflict(id) do nothing`;return {ok:true};}
