import type { AgeCurriculum } from "./types";

/** Verbatim coaching copy. Do not rewrite. */
export const AGE_CURRICULUM: AgeCurriculum[] = [
  { band: "8U", title: "Learn to compete and move", objectives: ["Athleticism and coordination", "Throwing accuracy and catching ability", "Body control and rhythm", "Competitiveness", "Understanding the mound", "Basic stretch and windup", "Throwing strikes", "Basic changeup feel", "Fielding the position", "Enjoying baseball"], avoid: ["No aggressive velocity program", "No pitch-design discussion", "No obsession with spin"] },
  { band: "9–10U", title: "Build the throw", objectives: ["Repeatable delivery", "Fastball location", "Changeup familiarity", "Basic pre-pitch routine", "Basic pickoff mechanics", "Fielding the position", "Simple competition", "Self-awareness"], avoid: ["Not six mechanical cues at once — the athlete should be able to answer 'what are you trying to do with this pitch?'"] },
  { band: "11–12U", title: "Learn to pitch", objectives: ["Fastball command", "Changeup confidence", "Repeatability", "Velocity emerging naturally through athletic development", "Pitch sequencing", "Holding runners", "Controlling emotions", "Understanding counts", "Workload education"], avoid: ["Don't build the athlete around breaking-ball dominance", "Fastball and changeup remain the emphasis"] },
  { band: "13–14U", title: "Build the pitcher — major transition", objectives: ["Delivery optimization", "Physical development", "Fastball identity", "Changeup identity", "Breaking-ball introduction when fastball and changeup competency exists", "Command", "Pitch sequences", "Mound presence", "Baserunner control", "Age-appropriate velocity development", "Competition", "Recovery and workload ownership"], avoid: ["95 game pitches max; four days of rest after 66–95 pitches"] },
  { band: "15–16U", title: "High-performance development", objectives: ["Force production, strength and mobility", "Delivery and velocity", "Fastball shape and secondary shapes", "Pitch separation and tunneling", "Command", "Arsenal fit and hitter strategy", "Game performance", "Physical development", "Nutrition and recovery education"], avoid: ["This is where ball-tracking data starts genuinely earning its keep"] },
  { band: "17–18U", title: "Individualized — one constraint at a time", objectives: ["Assessment → highest constraint → program → test → adapt", "One athlete needs +4 mph; another a legitimate third pitch", "Another better fastball location; another size and strength", "Another pitch selection; another recruiting exposure"], avoid: ["No two programs at this age should look the same"] },
];
