export const AGE_LOAD_BANDS = ["8-10", "11-12", "13-14", "15-16", "17-18", "College"] as const;
export type AgeLoadBand = (typeof AGE_LOAD_BANDS)[number];

export type LoadMode = "bodyweight" | "load" | "band" | "implement" | "isometric";

export type Exercise = {
  id: string;
  name: string;
  category: string;
  equipment: string;
  tempo: string;
  tempoWhy: string;
  loadMode: LoadMode;
  minAge: number;
  tracks: Array<"Pitching" | "Hitting" | "Catching" | "Two-way" | "All-around">;
  loads: Record<AgeLoadBand, string>;
  setup: string;
  howto: string;
  focus: string;
  mistakes: string[];
  why: string;
};

export const EXERCISES: Exercise[] = [
  {
    id: "trap-bar",
    name: "Trap-bar deadlift",
    category: "Main lift",
    equipment: "Trap bar",
    tempo: "2-1-X",
    tempoWhy: "A controlled lower loads the posterior chain; the pause kills bounce so the athlete owns the start; the up is intent, not a grind.",
    loadMode: "load",
    minAge: 13,
    tracks: ["Pitching", "Hitting", "Catching", "Two-way", "All-around"],
    loads: { "8-10": "not used", "11-12": "KB deadlift 20 lb", "13-14": "65–85 lb", "15-16": "95–135 lb", "17-18": "135–185 lb", College: "185–275 lb" },
    setup: "Stand inside the bar, mid-foot under the handles, brace before you pull.",
    howto: "Push the floor away. Hips and shoulders rise together. Stand tall, then lower on a two-count.",
    focus: "Force into the ground, not a yank with the low back.",
    mistakes: ["Rounding to get the weight up", "Hips shooting first", "Bouncing off the floor"],
    why: "Relative trap-bar strength is the most useful lower-body correlate we have for sprint speed, and it trains the exact hip extension the delivery uses.",
  },
  {
    id: "rfess",
    name: "Rear-foot elevated split squat",
    category: "Unilateral",
    equipment: "Bench + dumbbells",
    tempo: "3-1-1",
    tempoWhy: "The long eccentric is the lead-leg lesson: the front knee has to accept force slowly before it can block a delivery.",
    loadMode: "load",
    minAge: 11,
    tracks: ["Pitching", "Catching", "Two-way", "All-around"],
    loads: { "8-10": "bodyweight", "11-12": "bodyweight", "13-14": "15–25 lb", "15-16": "25–40 lb", "17-18": "40–60 lb", College: "50–95 lb" },
    setup: "Back foot on a bench, front shin vertical at the bottom, torso tall.",
    howto: "Drop the back knee. Pause. Drive through the front heel to stand.",
    focus: "Front leg does the work. Back leg is a kickstand.",
    mistakes: ["Lunging the front knee past the toe", "Collapsing the front hip", "Rushing the down"],
    why: "Pitching and catching both live on a firm front side. This is that position under load.",
  },
  {
    id: "goblet",
    name: "Goblet squat",
    category: "Main lift",
    equipment: "Kettlebell or dumbbell",
    tempo: "2-1-1",
    tempoWhy: "A pause at the bottom builds the deep squat catching needs and keeps youth athletes from bouncing out of the hole.",
    loadMode: "load",
    minAge: 8,
    tracks: ["Pitching", "Hitting", "Catching", "Two-way", "All-around"],
    loads: { "8-10": "8–12 lb", "11-12": "15–25 lb", "13-14": "25–40 lb", "15-16": "40–55 lb", "17-18": "50–70 lb", College: "60–90 lb" },
    setup: "Bell at the sternum, elbows in, feet just outside the hips.",
    howto: "Sit between the heels. Pause. Stand without the chest folding.",
    focus: "Torso stays over mid-foot.",
    mistakes: ["Heels lifting", "Elbows flaring and the chest dropping"],
    why: "It's the squat almost every age can load well, and the catcher's hip depth lives here.",
  },
  {
    id: "sl-rdl",
    name: "Single-leg RDL",
    category: "Unilateral",
    equipment: "Dumbbell",
    tempo: "3-0-1",
    tempoWhy: "Slow on the way down is how you find the hip on the stance leg after a growth spurt — speed hides the compensation.",
    loadMode: "load",
    minAge: 11,
    tracks: ["Pitching", "Hitting", "Two-way", "All-around"],
    loads: { "8-10": "bodyweight", "11-12": "bodyweight reach", "13-14": "10–20 lb", "15-16": "20–35 lb", "17-18": "30–45 lb", College: "40–60 lb" },
    setup: "Soft knee on the stance leg, square hips, free leg long behind.",
    howto: "Hinge until the torso is near parallel. Same-side hip does not hike. Stand by pushing the floor.",
    focus: "Both hips stay level. That's the rebalancing.",
    mistakes: ["Turning into a row", "Letting the hip dump out", "Bending the stance knee into a squat"],
    why: "Developing athletes after a growth spurt lose the map of a single-leg hinge. This puts it back, both sides, every session.",
  },
  {
    id: "lmj",
    name: "Lateral-to-medial jump",
    category: "Power",
    equipment: "Tape line",
    tempo: "X-X-X",
    tempoWhy: "No tempo. Power is the output, not the count. Stop the set the moment the jump shortens.",
    loadMode: "bodyweight",
    minAge: 13,
    tracks: ["Pitching", "Two-way", "All-around"],
    loads: { "8-10": "skip", "11-12": "skip", "13-14": "bodyweight", "15-16": "bodyweight", "17-18": "bodyweight", College: "bodyweight + hold" },
    setup: "Stand outside a line, load the outside leg, jump in and up.",
    howto: "Push the ground away laterally, stick the inside leg, hold two seconds.",
    focus: "Distance and a quiet landing. If either drops, the set is over.",
    mistakes: ["Spinning the hips", "Stutter-stepping into it", "Grinding extra reps after the jump dies"],
    why: "The most consistent lower-body correlate of throwing velocity we track. Programmed for output, not fatigue.",
  },
  {
    id: "broad",
    name: "Broad jump",
    category: "Power",
    equipment: "Tape",
    tempo: "X-X-X",
    tempoWhy: "Full recovery between reps. You are training the jump you just did, not the fifth one that is shorter.",
    loadMode: "bodyweight",
    minAge: 11,
    tracks: ["Hitting", "Pitching", "Two-way", "All-around"],
    loads: { "8-10": "play hops", "11-12": "bodyweight", "13-14": "bodyweight", "15-16": "bodyweight", "17-18": "bodyweight", College: "bodyweight" },
    setup: "Athletic stance, arms back, jump out, stick it.",
    howto: "Load, throw the arms, land quietly on two feet. Walk back. Wait.",
    focus: "Stick the landing. A hop on landing does not count.",
    mistakes: ["Rushing the next rep", "Sitting into a squat instead of jumping"],
    why: "Horizontal power is the same quality as a stride and a first step. Quality or it is just jumping around.",
  },
  {
    id: "mb-rot",
    name: "Rotational med-ball throw",
    category: "Rotational",
    equipment: "Med-ball + wall",
    tempo: "X-X-X",
    tempoWhy: "The ball is last. If you time the throw you lose the sequence the swing and the delivery both need.",
    loadMode: "implement",
    minAge: 11,
    tracks: ["Hitting", "Pitching", "Two-way"],
    loads: { "8-10": "2 lb", "11-12": "4 lb", "13-14": "6 lb", "15-16": "8 lb", "17-18": "10 lb", College: "10–12 lb" },
    setup: "Side-on to a wall, ball at the hip, step behind, throw through the wall.",
    howto: "Hips lead. Ball leaves late. Both sides.",
    focus: "Hips first, ball last. Same as the swing.",
    mistakes: ["Arming it", "Same-side every time", "A ball so heavy the hips stall"],
    why: "Rotational med-ball throw velocity tracks bat speed and throwing velocity better than any jump we have.",
  },
  {
    id: "mb-chest",
    name: "Med-ball chest pass",
    category: "Power",
    equipment: "Med-ball + wall",
    tempo: "X-X-X",
    tempoWhy: "Intent into the wall. A slow pass is a core exercise in disguise — that is not why it is here.",
    loadMode: "implement",
    minAge: 8,
    tracks: ["All-around", "Hitting", "Catching"],
    loads: { "8-10": "2–4 lb", "11-12": "4 lb", "13-14": "6 lb", "15-16": "8 lb", "17-18": "10 lb", College: "10–12 lb" },
    setup: "Athletic stance, ball at the chest, punch it through the wall, catch the rebound or let it drop.",
    howto: "Triple-extend. The arms finish what the legs start.",
    focus: "Floor first, then the ball.",
    mistakes: ["Arm-only punch", "Catching every rebound into a sloppy set"],
    why: "A clean, low-skill power expression for youth and for return-to-play when rotation is still off the table.",
  },
  {
    id: "ytw",
    name: "Prone Y-T-W",
    category: "Cuff",
    equipment: "Floor or light plates",
    tempo: "2-2-2",
    tempoWhy: "The cuff's job in a delivery is eccentric. Slow holds are how you train that instead of flapping the arms.",
    loadMode: "bodyweight",
    minAge: 8,
    tracks: ["Pitching", "Catching", "Two-way", "All-around"],
    loads: { "8-10": "bodyweight", "11-12": "bodyweight", "13-14": "1–2 lb", "15-16": "2.5 lb", "17-18": "2.5–5 lb", College: "5 lb" },
    setup: "Face down, thumbs up, forehead on a towel.",
    howto: "Raise to a Y, hold. T, hold. W, hold. Lower slower than you lifted.",
    focus: "Shoulder blades on the back, not shrugged to the ears.",
    mistakes: ["Bending the elbows on the Y", "Rushing the hold", "Going heavy enough to cheat with the traps"],
    why: "Pitching activates the cuff before the arm path exists. This is that activation under control.",
  },
  {
    id: "er",
    name: "Side-lying external rotation",
    category: "Cuff",
    equipment: "Light dumbbell",
    tempo: "3-1-3",
    tempoWhy: "Deceleration is the expensive part of the throw. The lowering half is the work.",
    loadMode: "load",
    minAge: 11,
    tracks: ["Pitching", "Two-way"],
    loads: { "8-10": "skip", "11-12": "1–2 lb", "13-14": "3–5 lb", "15-16": "5 lb", "17-18": "5–8 lb", College: "8–10 lb" },
    setup: "Side-lying, elbow on the ribcage, forearm starting on the stomach.",
    howto: "Rotate the forearm up. Pause. Lower on a three-count. Do not let the elbow leave the side.",
    focus: "Small range, honest tempo.",
    mistakes: ["Rolling the body to get the weight up", "A weight that turns this into a press"],
    why: "Extra cuff work is the velocity block's health tax. You do not get the power volume without this.",
  },
  {
    id: "reverse-throw",
    name: "Reverse throws",
    category: "Cuff",
    equipment: "Band or 1–2 lb plyo",
    tempo: "1-0-3",
    tempoWhy: "Fast back, slow down. You are training the brakes, not the throw.",
    loadMode: "band",
    minAge: 11,
    tracks: ["Pitching", "Catching", "Two-way"],
    loads: { "8-10": "light band", "11-12": "light band", "13-14": "1 lb plyo", "15-16": "1–2 lb", "17-18": "2 lb", College: "2 lb" },
    setup: "Square to a partner or a wall, ball or band at the hip, throw backwards over the same-side shoulder.",
    howto: "Flip it back. Catch the deceleration with the cuff, not a shrug.",
    focus: "Quiet neck. The arm does the slowing.",
    mistakes: ["Turning it into a high-intent throw", "Using a ball heavy enough to yank the elbow"],
    why: "Deceleration capacity is what lets a velocity block exist. Without it, more power is just more stress.",
  },
  {
    id: "pallof",
    name: "Pallof press",
    category: "Core",
    equipment: "Band or cable",
    tempo: "2-2-2",
    tempoWhy: "The hold is the point. Anti-rotation is a refusal to turn, not a twist with a band.",
    loadMode: "band",
    minAge: 8,
    tracks: ["Hitting", "Catching", "All-around", "Two-way"],
    loads: { "8-10": "light band", "11-12": "light band", "13-14": "medium", "15-16": "medium", "17-18": "heavy", College: "heavy" },
    setup: "Side-on to the anchor, band at the sternum, feet planted.",
    howto: "Press the hands straight out. Hold. Do not let the ribcage turn toward the anchor. Both sides.",
    focus: "Hips and shoulders stay square.",
    mistakes: ["Leaning away from the band", "Turning the press into a rotation"],
    why: "Hitting needs anti-rotation so the pelvis can turn under a quiet torso. This is that quality with no bat in the way.",
  },
  {
    id: "copenhagen",
    name: "Copenhagen plank",
    category: "Core",
    equipment: "Bench",
    tempo: "Hold",
    tempoWhy: "A timed hold. Adductor capacity is what lets a catcher stay in a deep squat without the knees diving in.",
    loadMode: "isometric",
    minAge: 13,
    tracks: ["Catching", "Two-way", "All-around"],
    loads: { "8-10": "skip", "11-12": "side plank", "13-14": "short lever 15s", "15-16": "20–25s", "17-18": "25–30s", College: "30–40s" },
    setup: "Side plank with the top foot or shin on a bench, bottom leg hovering or tucked.",
    howto: "Hips up. Body in a line. Breathe. Switch sides.",
    focus: "The top inner thigh does the work, not the shoulder.",
    mistakes: ["Hips sagging", "Holding the breath", "Only training the strong side"],
    why: "Catching adds Copenhagen because the position is a long isometric on the adductors. You cannot squat your way into that.",
  },
  {
    id: "deep-squat",
    name: "Deep squat hold",
    category: "Mobility",
    equipment: "None, or a light plate as a counterweight",
    tempo: "Hold",
    tempoWhy: "Time in the hole. Catchers who cannot sit here will find a one-knee cheat by the fourth inning.",
    loadMode: "isometric",
    minAge: 8,
    tracks: ["Catching", "All-around"],
    loads: { "8-10": "20s play", "11-12": "20–30s", "13-14": "30s", "15-16": "40s", "17-18": "45s", College: "45–60s" },
    setup: "Feet just outside the hips, heels down, elbows inside the knees.",
    howto: "Sit. Breathe into the belly. Drive the knees out with the elbows. Stand without using the hands.",
    focus: "Heels stay down. Chest stays up.",
    mistakes: ["Rolling onto the toes", "Holding with a rounded back and calling it depth"],
    why: "Catching adds a deep squat because the receiving position is a mobility problem before it is a strength problem.",
  },
  {
    id: "farmer",
    name: "Farmer carry",
    category: "Conditioning",
    equipment: "Dumbbells or kettlebells",
    tempo: "Walk",
    tempoWhy: "Upright, braced walking. This is capacity, not a race. Return-to-play lives here.",
    loadMode: "load",
    minAge: 8,
    tracks: ["All-around", "Catching", "Two-way", "Pitching"],
    loads: { "8-10": "8 lb each", "11-12": "12 lb", "13-14": "20 lb", "15-16": "30 lb", "17-18": "40–50 lb", College: "50–70 lb" },
    setup: "Heavy enough that the grip talks, light enough that the ribcage stays stacked.",
    howto: "Walk a line. Short steps. Put them down like you meant it.",
    focus: "Tall. Quiet. No lean.",
    mistakes: ["Leaning into one side", "Shuffling into a trudge", "A load that turns the walk into a lean"],
    why: "High-rep, long-rest capacity work. Return-to-play uses this instead of jumps because output is not the goal yet.",
  },
  {
    id: "iso-split",
    name: "Isometric split-stance hold",
    category: "Unilateral",
    equipment: "Bodyweight or light kettlebell",
    tempo: "Hold",
    tempoWhy: "Nothing above a seven. The hold builds the position without asking the tendon for a concentric.",
    loadMode: "isometric",
    minAge: 8,
    tracks: ["Pitching", "Catching", "All-around", "Two-way"],
    loads: { "8-10": "bodyweight 20s", "11-12": "20s", "13-14": "25s", "15-16": "30s", "17-18": "30s + KB", College: "30–40s + KB" },
    setup: "Long lunge, front shin vertical, back knee hovering an inch.",
    howto: "Hold. Breathe. Switch. The front heel stays glued.",
    focus: "Position over burn. If the form goes, the hold is over.",
    mistakes: ["Dropping the back knee to rest", "Letting the front heel peel"],
    why: "Return-to-play starts with capacity in the positions that got the athlete hurt — not with the lift that used to impress them.",
  },
  {
    id: "row",
    name: "Chest-supported row",
    category: "Main lift",
    equipment: "Bench + dumbbells",
    tempo: "2-1-2",
    tempoWhy: "A pause on the chest keeps the upper back in the lift. Size blocks need this volume; velocity blocks need the posture.",
    loadMode: "load",
    minAge: 11,
    tracks: ["All-around", "Hitting", "Pitching", "Two-way"],
    loads: { "8-10": "band row", "11-12": "10 lb", "13-14": "20 lb", "15-16": "30–40 lb", "17-18": "40–55 lb", College: "50–70 lb" },
    setup: "Chest on a bench, arms hanging, thumbs in.",
    howto: "Pull to the hip pocket. Pause. Lower on a two-count.",
    focus: "Elbows sweep, neck stays long.",
    mistakes: ["Shrugging to the ears", "Yanking with the low back off the bench"],
    why: "Scapular capacity is the platform the arm throws from. Size gets extra sets; everyone else gets honest ones.",
  },
  {
    id: "pushup",
    name: "Push-up",
    category: "Main lift",
    equipment: "Floor",
    tempo: "3-1-1",
    tempoWhy: "Size wants the long eccentric. Return-to-play wants the same tempo at a lower RPE so the anterior shoulder is not dumped into.",
    loadMode: "bodyweight",
    minAge: 8,
    tracks: ["All-around", "Hitting", "Catching", "Two-way"],
    loads: { "8-10": "knee or full", "11-12": "full", "13-14": "full", "15-16": "full or weighted", "17-18": "weighted", College: "weighted" },
    setup: "Hands under the shoulders, body in a line.",
    howto: "Lower on a three-count. Chest to a fist off the floor. Press without the hips sagging.",
    focus: "One piece. No snake.",
    mistakes: ["Flaring the elbows to 90", "Only moving the head"],
    why: "Upper-body volume that does not need a bench. Size piles sets; RTP keeps it easy.",
  },
  {
    id: "clams",
    name: "Side-lying hip rotator",
    category: "Mobility",
    equipment: "Mini-band optional",
    tempo: "2-1-2",
    tempoWhy: "The hip rotators have to fire before a swing or a block. Fast reps skip them and let the TFL cheat.",
    loadMode: "band",
    minAge: 8,
    tracks: ["Hitting", "Catching", "All-around"],
    loads: { "8-10": "no band", "11-12": "no band", "13-14": "light band", "15-16": "light", "17-18": "medium", College: "medium" },
    setup: "Side-lying, knees bent, heels together.",
    howto: "Open the top knee without rolling the pelvis back. Pause. Lower slow. Both sides.",
    focus: "Pelvis stays stacked.",
    mistakes: ["Rolling onto the back to get range", "A band so heavy the hip flexor takes over"],
    why: "Hitting programs the hip rotators so the pelvis can turn. Catching needs the same muscles to hold a squat.",
  },
  {
    id: "windmill-circle",
    name: "Windmill circle (no ball)",
    category: "Softball",
    equipment: "None",
    tempo: "Smooth",
    tempoWhy: "The circle is a rhythm problem first. A rushed circle is a late whip. Slow enough to feel the brush at the hip.",
    loadMode: "bodyweight",
    minAge: 8,
    tracks: ["Pitching"],
    loads: { "8-10": "unloaded", "11-12": "unloaded", "13-14": "1 lb", "15-16": "1 lb", "17-18": "1–2 lb", College: "1–2 lb" },
    setup: "Stride foot toward the target, arm long, start at the hip.",
    howto: "Full circle, brush the hip, finish tall. Then walk-through circles. Then K-position holds.",
    focus: "Long arm. Same speed through the bottom.",
    mistakes: ["Bending the elbow to 'get whip'", "Pausing at the K", "A weighted ball on a sore arm"],
    why: "Softball adds a windmill progression because the circle is the delivery. Baseball cuff work does not replace it.",
  },
];

export function exerciseById(id: string) {
  return EXERCISES.find((row) => row.id === id);
}

export function loadBandForAge(age: number, college = false): AgeLoadBand {
  if (college || age >= 19) return "College";
  if (age <= 10) return "8-10";
  if (age <= 12) return "11-12";
  if (age <= 14) return "13-14";
  if (age <= 16) return "15-16";
  return "17-18";
}
