import type { Flaw } from "./types";

/** Verbatim coaching copy. Do not rewrite. */
export const FLAWS: Flaw[] = [
  { id: "fl1", discipline: "Pitching", name: "Flying open / early trunk rotation", looksLike: "Front shoulder and chest open before foot strike; misses arm-side and up.", drills: ["d9", "d10", "d1"], cues: ["Show the hitter your back pocket longer", "Land closed, then turn", "Chest stays behind the front hip until the foot is down"], why: "Early rotation dumps energy before the front leg can accept it. It costs velocity and command at the same time." },
  { id: "fl2", discipline: "Pitching", name: "Rushing / tempo too fast", looksLike: "Arm is late, body is early; misses up and arm-side; feels 'out of sync'.", drills: ["d5", "d6", "d4"], cues: ["Slow is smooth, smooth is fast", "Lift on one, land on three", "Let the arm catch up"], why: "The arm can only be on time if the body gives it time. Tempo is fixed with rhythm, not with arm cues." },
  { id: "fl3", discipline: "Pitching", name: "Poor direction / striding across the body", looksLike: "Front foot lands closed across the line; throws across the body; glove-side misses.", drills: ["d3", "d2", "d1"], cues: ["Land where you look", "Foot on the line", "Lead with the hip, not the knee"], why: "Direction problems are sequencing problems. Fix the pelvis and the foot follows." },
  { id: "fl4", discipline: "Pitching", name: "Soft front leg / no block", looksLike: "Front knee keeps drifting forward through release; no snap; velocity leaks.", drills: ["d9", "d10"], cues: ["Post the front leg", "Chest over a firm front side", "Land and stop the knee"], why: "The front leg converts forward momentum into rotation. Soft front leg, soft fastball." },
  { id: "fl5", discipline: "Pitching", name: "Arm drag / late arm", looksLike: "Arm is behind the body at foot strike; low elbow at release; arm-side misses and a sore front shoulder.", drills: ["d7", "d8", "d4"], cues: ["Get the ball up on time", "Hand above the elbow at foot strike", "Let the arm go, don't push it"], why: "A late arm gets whipped by the trunk instead of riding it. That's stress on the elbow and shoulder, not velocity." },
  { id: "fl6", discipline: "Pitching", name: "Collapsing back leg / no momentum", looksLike: "Sinks straight down on the back leg; slow to the plate; everything looks effortful.", drills: ["d4", "d5", "d2"], cues: ["Move down the mound, not down into it", "Build speed into the throw", "Stay tall, go forward"], why: "A delivery with no momentum asks the arm to make up the difference." },
  { id: "fl7", discipline: "Pitching", name: "Head pulls off target", looksLike: "Head yanks glove-side at release; misses glove-side and high.", drills: ["d11", "d13", "d1"], cues: ["Eyes to the cell through release", "Nose to the target", "Finish with the head still"], why: "Where the head goes the body follows. A still head is a free command gain." },
  { id: "fl8", discipline: "Pitching", name: "Inconsistent release / no repeatability", looksLike: "Misses in every direction; good pitch then a bad one with no pattern.", drills: ["d11", "d12", "d9"], cues: ["Same tempo every pitch", "Call the pitch out loud", "Feel the finish"], why: "Command is repeatability. Score every pitch and the pattern shows up." },
  { id: "fl9", discipline: "Pitching", name: "Cutting the fastball / poor pronation", looksLike: "Fastball runs glove-side with cut; arm-side misses when trying to correct.", drills: ["d15", "d7"], cues: ["Thumb down through release", "Throw through the inside of the ball", "Finish with the palm out"], why: "Getting around the ball is a grip-and-release problem before it's a mechanics problem." },
  { id: "fl10", discipline: "Pitching", name: "No hip-shoulder separation", looksLike: "Hips and shoulders turn together; low velocity for the athlete's size; arm-only delivery.", drills: ["d1", "d4", "d7"], cues: ["Hips first, chest late", "Feel the stretch across the front", "Let the hips lead"], why: "Separation is where free velocity lives. It's trained, not cued." },
  { id: "fl11", discipline: "Hitting", name: "Casting / bat drag", looksLike: "Hands cast away from the body early; long swing; late on velocity.", drills: ["h1", "h4", "h2"], cues: ["Hands inside the ball", "Knob to the pitcher", "Stay connected"], why: "A long swing is a slow swing. Connection is speed." },
  { id: "fl12", discipline: "Hitting", name: "Early hip opening / pulling off", looksLike: "Front hip flies open; rolls over; can't hit the outer third.", drills: ["h2", "h3", "h6"], cues: ["Let the ball travel", "Hit the inside of the ball", "Stay closed with the front side"], why: "Opening early trades power for pull. The opposite-field tee fixes it without a single cue." },
  { id: "fl13", discipline: "Hitting", name: "Lunging / drifting forward", looksLike: "Weight on the front foot before the swing; off-speed eats them alive.", drills: ["h3", "h4"], cues: ["Land, then decide", "Stay back", "Stride to balance"], why: "Timing problems are rhythm problems. Separate the stride from the swing." },
  { id: "fl14", discipline: "Hitting", name: "Arms-only swing / no separation", looksLike: "Hips and hands move together; bat speed low for the athlete's strength.", drills: ["h4", "h5"], cues: ["Hips first, hands late", "Feel the stretch", "Turn the back hip"], why: "Bat speed comes from sequencing. Arms-only swings plateau." },
  { id: "fl15", discipline: "Hitting", name: "Rolling over / top-hand dominance", looksLike: "Weak ground balls to the pull side; barrel rolls over at contact.", drills: ["h1", "h2"], cues: ["Palm up, palm down through contact", "Barrel stays in the zone", "Finish high"], why: "The top hand taking over is the most common cause of weak contact." },
  { id: "fl16", discipline: "Hitting", name: "Chasing / no plan", looksLike: "Swings at pitches out of the plan; strikeouts on balls.", drills: ["h6", "h3"], cues: ["Have a plan before the pitch", "Take is a win", "Hunt your pitch"], why: "Swing decisions are a trained skill, and they're charted here." },
  { id: "fl17", discipline: "Catching", name: "Loud hands / pushing strikes out", looksLike: "Mitt moves away from the zone on the catch; borderline strikes called balls.", drills: ["c1", "c2"], cues: ["Beat it to the spot", "Stick it", "Work the ball back to the middle"], why: "Framing is quiet hands and a still body. Bare-hand work fixes it fastest." },
  { id: "fl18", discipline: "Catching", name: "Standing up on blocks", looksLike: "Rises out of the block; ball goes off the chest and away.", drills: ["c3"], cues: ["Chin down", "Chest over the ball", "Stay down until it's dead"], why: "The block is a drop, not a stand. Reps until it's a reflex." },
  { id: "fl19", discipline: "Catching", name: "Slow exchange", looksLike: "Pop time 0.2 slower than the arm should produce; looks at the transfer.", drills: ["c4", "c5"], cues: ["Ball to the ear", "Feet before hands finish", "Don't look at the transfer"], why: "Most catchers cut 0.1–0.2 in the exchange alone. Arm strength isn't the first fix." },
  { id: "fl20", discipline: "Catching", name: "Footwork misaligned to second", looksLike: "Throws sail arm-side; hips point toward first.", drills: ["c5", "c4"], cues: ["Jab, replace, throw", "Hips to the bag", "Two clean steps beat three fast ones"], why: "Clean footwork lines the hips up. The arm can't fix bad feet." },
  { id: "fl21", discipline: "Pitching", name: "Drive-leg collapse (windmill)", looksLike: "No push off the rubber; short stride; velocity well below arm speed.", drills: ["d4", "d9"], cues: ["Push the rubber away", "Drive through the circle", "Land firm, finish tall"], why: "Windmill velocity is the drive leg first. Everything else is second.", sport: "softball" },
];
