import type { Discipline, GameIqModule } from "./types";

/** Verbatim coaching copy. Do not rewrite. */
export const IQ_PITCHING: GameIqModule[] = [
  { id: "p-routine", t: "Pre-pitch routine", band: "youth", why: "A repeatable routine is the only thing that stays constant when the game speeds up.", teach: "Build a five-second sequence: get the sign, breathe out, set the feet, pick the target, go. Run it on every pitch of the bullpen, including between pitches.", check: "Same routine on 20 of 20 pitches without a reminder." },
  { id: "p-breath", t: "Breathing and reset", band: "youth", why: "Heart rate spikes after a walk or an error. A reset breath is a trainable off-ramp.", teach: "Teach a 4-second in, 6-second out behind the mound. Trigger it deliberately after any bad pitch in the pen.", check: "Athlete resets without being told after a noncompetitive pitch." },
  { id: "p-strike1", t: "Working ahead", band: "youth", why: "First-pitch strikes collapse a hitter's options more than any secondary pitch.", teach: "Score first-pitch strike percentage every bullpen. Make the first pitch of each simulated at-bat count double.", check: "First-pitch strike rate above 60%." },
  { id: "p-fielding", t: "Fielding the position", band: "youth", why: "The pitcher is a fifth infielder the moment the ball leaves his hand.", teach: "Comebackers, covering first, and the 1-6-3. Ten reps at the end of a session.", check: "Gets off the mound and covers first without thinking." },
  { id: "p-bunt", t: "Bunt defense", band: "developing", why: "One blown bunt play gives away an inning.", teach: "Walk through the coverage on a bunt to each side, calling the base out loud.", check: "Calls the base before he fields it." },
  { id: "p-runners", t: "Holding runners", band: "developing", why: "A pitcher who can't hold a runner turns every single into a double.", teach: "Vary the hold, teach the slide step, time the delivery to the plate. Target 1.3 seconds or faster.", check: "Delivery to plate under 1.4 seconds from the stretch." },
  { id: "p-speeds", t: "Changing speeds", band: "developing", why: "Timing is what hitters actually have. Speed changes take it away.", teach: "Fastball/changeup pairs in the bullpen with the same arm speed. Chart the velocity gap.", check: "8+ mph separation with no arm-speed change." },
  { id: "p-eye", t: "Changing eye levels", band: "developing", why: "A hitter who has to cover top and bottom of the zone covers neither well.", teach: "Called sequences that deliberately move up then down. Score whether the athlete executed the level change.", check: "Executes an up-down sequence 6 of 10 times." },
  { id: "p-inside", t: "Pitching inside", band: "developing", why: "Without the inner third, the outer third stops working.", teach: "Inner-third targets at reduced intent first, then game intent. Address the fear directly.", check: "Will throw inside on command in a simulated at-bat." },
  { id: "p-walk", t: "After you walk someone", band: "developing", why: "The pitch after a walk is the most predictable pitch in baseball — and hitters know it.", teach: "Simulate: issue a walk, then require a competitive strike on the next pitch after a full reset.", check: "Strike on the next pitch 7 of 10 times." },
  { id: "p-2strike", t: "Expanding with two strikes", band: "developing", why: "Two-strike pitches are supposed to be chased, not hit. Most young pitchers throw them in the zone.", teach: "0-2 and 1-2 counts only. Score only quality chase locations — a strike down the middle scores zero.", check: "Chase-quality location on 6 of 10 two-strike pitches." },
  { id: "p-lost", t: "When the mechanics disappear", band: "developing", why: "Every pitcher loses it mid-inning. The ones who survive have one cue, not five.", teach: "Pick the single cue that resets this athlete. Practice going to it mid-bullpen after a bad stretch.", check: "Names his own reset cue without prompting." },
  { id: "p-read", t: "Reading hitters", band: "advanced", why: "Stance, stride, timing and swing path tell you what to throw next.", teach: "Film study or live: identify setup depth, stride timing and where the last swing was late or early.", check: "Can state a plan for a hitter after two pitches." },
  { id: "p-seq", t: "Sequencing", band: "advanced", why: "Pitches work in pairs and threes, not alone.", teach: "Build three-pitch sequences on paper, then execute them in a competition bullpen and grade execution.", check: "Executes a planned three-pitch sequence in order." },
  { id: "p-tunnel", t: "Tunneling", band: "advanced", why: "Two pitches that look identical for the first 20 feet are worth more than two good pitches that don't.", teach: "Fastball and secondary to the same tunnel point, video from behind. Compare release and early flight.", check: "Fastball and secondary share a release window on video." },
  { id: "p-timing", t: "Understanding swing timing", band: "advanced", why: "Knowing why a hitter is late tells you whether to repeat the pitch or change it.", teach: "Watch swings against his own bullpen. Classify each as early, on time or late, and decide the next pitch.", check: "Correctly classifies timing on 8 of 10 swings." },
  { id: "p-select", t: "Pitch selection", band: "advanced", why: "The best pitch is situational, not a favorite.", teach: "Coach calls count, runners and handedness. Athlete picks and defends the choice out loud.", check: "Reasoning holds up on 8 of 10 calls." },
  { id: "p-running", t: "Controlling the running game", band: "advanced", why: "Times to the plate, varied holds and pickoffs are a package, not a single skill.", teach: "Combine slide step, hold variation and pickoff timing in one simulated inning.", check: "Runner cannot time the delivery over ten pitches." },
  { id: "p-fatigue", t: "Recognizing fatigue", band: "advanced", why: "Arm slot drops before the athlete feels tired. Knowing his own tells prevents injury.", teach: "Chart velocity and arm slot across a long bullpen; show the athlete his own drop-off point.", check: "Athlete names his own fatigue tells." },
  { id: "p-compete", t: "Competing without your best stuff", band: "advanced", why: "Most starts are made on a B-minus arsenal. That is the skill that separates.", teach: "Deliberately restrict him to two pitches at 85% and require six outs in a simulated game.", check: "Gets through simulated innings without his best pitch." },
  { id: "p-presence", t: "Mound presence", band: "advanced", why: "Body language tells the dugout, the defense and the hitter whether you're beaten.", teach: "Film the pen. Watch it back with the sound off and grade what the body said.", check: "Same posture after a bad pitch as a good one." },
];

export const IQ_HITTING: GameIqModule[] = [
  { id: "h-routine", t: "Pre-pitch routine and timing trigger", band: "youth", why: "Hitting is a timing skill; the trigger has to start on schedule every pitch.", teach: "Same setup, same breath, same load trigger on every rep from the tee through live.", check: "Identical routine on 20 swings." },
  { id: "h-zone", t: "Owning your zone", band: "youth", why: "Swinging at your pitch is the highest-return skill in hitting.", teach: "Call a zone before each front toss; taking the wrong pitch scores the same as a hit.", check: "Swings only in-plan on 8 of 10." },
  { id: "h-count", t: "Count leverage", band: "developing", why: "The strike zone should physically change size in the hitter's mind by count.", teach: "Run 1-0 and 0-2 rounds with different swing rules and score decisions, not contact.", check: "Different approach visible between 1-0 and 0-2 rounds." },
  { id: "h-2strike", t: "Two-strike approach", band: "developing", why: "A shorter, flatter, later swing keeps at-bats alive.", teach: "Choke up, widen, shorten. Ten two-strike-only at-bats, contact scored above damage.", check: "Contact rate above 80% with two strikes." },
  { id: "h-recog", t: "Pitch recognition", band: "developing", why: "You can't hit what you identify late.", teach: "Machine or live with call-outs — the hitter names the pitch out loud before swinging.", check: "Names the pitch correctly on 8 of 10." },
  { id: "h-situ", t: "Situational hitting", band: "developing", why: "Runner on second and nobody out is a different at-bat than leading off.", teach: "Assign the situation before each round: move the runner, drive him in, extend the inning.", check: "Executes the job on 7 of 10." },
  { id: "h-plan", t: "Building an at-bat plan", band: "advanced", why: "Good hitters hunt something specific and adjust from there.", teach: "Scout the pitcher's arsenal, choose the hunt pitch and the adjust plan before the round.", check: "Can state the plan and how he'd adjust." },
  { id: "h-oppo", t: "Using the whole field", band: "advanced", why: "A hitter who can only pull gets pitched away all night.", teach: "Score only balls hit hard the other way for a full round.", check: "Hard contact oppo on 6 of 10 outer-third pitches." },
];

export const IQ_CATCHING: GameIqModule[] = [
  { id: "c-secondary", t: "Stance selection", band: "youth", why: "The wrong stance with a runner on costs the throw before the pitch arrives.", teach: "Primary with bases empty, secondary with runners. Call the situation before each pitch.", check: "Correct stance on every situation called." },
  { id: "c-signs", t: "Signs and sequences with runners", band: "developing", why: "Giving away the pitch is worse than calling the wrong one.", teach: "Practice sign sequences with a runner at second and an active decoy.", check: "Sequence stays clean under a live runner." },
  { id: "c-staff", t: "Managing a pitcher", band: "developing", why: "The catcher is the only player who can slow the game down for a struggling pitcher.", teach: "Rehearse the mound visit: what to say, what not to say, when to go.", check: "Runs a useful visit in under 20 seconds." },
  { id: "c-call", t: "Calling a game", band: "advanced", why: "Sequencing from behind the plate is a coaching skill the athlete can own.", teach: "Catcher calls a full simulated inning and defends each call afterward.", check: "Reasoning holds up on 8 of 10 calls." },
  { id: "c-scout", t: "Reading hitters from behind the plate", band: "advanced", why: "The catcher sees the stride, the stance depth and the swing path better than anyone.", teach: "Chart hitter tendencies live and adjust the sequence within the at-bat.", check: "Adjusts a sequence based on a swing he read." },
];

export const IQ_BY_DISCIPLINE: Record<Exclude<Discipline, "Fielding">, GameIqModule[]> = {
  Pitching: IQ_PITCHING,
  Hitting: IQ_HITTING,
  Catching: IQ_CATCHING,
};
