import { PD_POLICY } from "@/lib/pd";
import type { DevelopmentData } from "./types";

export function emptyDevelopment(): DevelopmentData {
  return {
    athletes: [],
    families: [],
    coaches: [],
    services: [],
    packages: [],
    memberships: [],
    bookings: [],
    availability: [],
    waitlist: [],
    leads: [],
    outings: [],
    workoutLog: [],
    strengthLog: [],
    pointsLog: [],
    scorecards: [],
    evaluations: [],
    lessons: [],
    filmReviews: [],
    interventions: [],
    calibration: [],
    calibrationScores: [],
    policy: {
      freeCancelHours: PD_POLICY.freeCancelHours,
      partialRefundHours: PD_POLICY.partialRefundHours,
      lateCancelFeePct: PD_POLICY.lateCancelFeePct,
      noShowFeePct: PD_POLICY.noShowFeePct,
      newFamilyCredit: PD_POLICY.newFamilyCredit,
      rescheduleDaysNotice: PD_POLICY.rescheduleDaysNotice,
      reschedulesPerMonth: PD_POLICY.reschedulesPerMonth,
      verifyActivities: true,
    },
    coachPayouts: [],
    coachOverrides: [],
    benchmarks: [],
    certifications: [],
    auditLog: [],
    messages: [],
    plans: [],
    diagnose: [],
    cohorts: [],
    gameIq: [],
    reportCards: [],
    velocity: [],
    goals: [],
    arsenal: [],
    pitchDesign: [],
    skillPlans: [],
    warmups: [],
    strengthSets: [],
    throwingAssignments: [],
    bullpens: [],
    workload: [],
    armCare: [],
    physicalTests: [],
    metrics: [],
    recruiting: [],
    intake: [],
    videos: [],
    documents: [],
    videoStandards: [],
  };
}