-- Generated from migrations/0008_catalog.sql; do not edit this copy.
CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
DO $netlify_apply$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM _migrations WHERE name = '0008_catalog.sql') THEN
-- Generated from pricing.ts/catalog.ts/club.ts. Initial seed only; reads never reset prices.
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s1','lesson','New Pitcher Assessment','Pitching',149,75,0,0,0,0,true,false,false,'Required entry point. 75 minutes, not an ordinary lesson.','','[]','{}',true,10) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s2','lesson','Private Development 30','Pitching',60,30,0,0,0,0,false,false,true,'Focused recurring session.','','[]','{}',true,11) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s3','lesson','Private Development 60','Pitching',100,60,0,0,0,0,false,false,true,'Full development session.','','[]','{}',true,12) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s4','lesson','Pitching Lab / Reassessment','Pitching',129,60,0,0,0,0,false,false,false,'Objective testing and pitch design.','','[]','{}',true,13) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s5','lesson','Remote Video Review','Pitching',45,20,0,0,0,0,false,false,true,'Asynchronous film feedback.','','[]','{}',true,14) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s6','lesson','Small-Group Pitcher Development','Pitching',159,75,0,0,0,0,false,true,false,'Weekly coached training, 3–5 pitchers. Billed monthly.','','[]','{}',true,15) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s7','lesson','Private Hitting 30','Hitting',60,30,0,0,0,0,false,false,true,'Focused recurring session.','','[]','{}',true,16) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s8','lesson','Private Hitting 60','Hitting',100,60,0,0,0,0,false,false,true,'Full development session.','','[]','{}',true,17) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s9','lesson','Hitting Assessment','Hitting',150,60,0,0,0,0,false,false,false,'Baseline swing, contact and power.','','[]','{}',true,18) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s10','lesson','Private Catching 30','Catching',60,30,0,0,0,0,false,false,true,'Focused recurring session.','','[]','{}',true,19) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s11','lesson','Private Catching 60','Catching',100,60,0,0,0,0,false,false,true,'Full development session.','','[]','{}',true,20) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('s12','lesson','Private Fielding 60','Fielding',100,60,0,0,0,0,false,false,true,'Infield or outfield development.','','[]','{}',true,21) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('p1','package','4-Session Package (30 min)','Cage',220,30,4,0,120,0,false,false,false,'','','[]','{}',true,100) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('p2','package','4-Session Package (60 min)','Cage',385,60,4,0,120,0,false,false,false,'','','[]','{}',true,101) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('p3','package','8-Session Package (60 min)','Cage',740,60,8,0,180,0,false,false,false,'','','[]','{}',true,102) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('m1','membership','Development Membership','Pitching',239,30,4,0,0,0,false,false,false,'','Four 30-minute sessions plus the development system.','["Four 30-minute sessions","Athlete profile","Personal development priorities","Drill library assignments","Session recaps","Throwing and workload tracking","Monthly progress update"]','{}',true,200) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('m2','membership','Performance Membership','Pitching',389,60,4,1,0,0,false,false,false,'','Four 60-minute sessions plus video and pitch development.','["Four 60-minute sessions","Everything in Development","Video analysis","Expanded command work","Pitch development","Periodic reassessment","Game-performance tracking","Priority recurring slot"]','{}',true,201) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('m3','membership','Elite Hybrid Membership','Pitching',449,60,4,4,0,0,false,false,false,'','Everything in Performance plus film review and higher-touch support.','["Everything in Performance","One monthly game-film review","Higher-touch asynchronous video feedback","Monthly roadmap update","Quarterly Pitching Lab / advanced assessment","Priority scheduling"]','{}',true,202) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('m4','membership','Small-Group Development','Pitching',159,75,4,0,0,0,false,false,false,'','One 75-minute group session weekly, 3–5 comparable pitchers.','["Weekly 75-minute group session","Command competition and mound situations","Athlete profile","Session recaps"]','{}',true,203) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('m5','membership','Remote HS Pitching Coaching','Pitching',179,0,0,4,0,0,false,false,false,'','Fully remote programming and film feedback.','["Monthly programming","Four video reviews","Throwing and workload tracking","Monthly roadmap update"]','{}',true,204) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('individual','cage','Individual cage','Cage',50,60,0,0,0,0,false,false,false,'','','[]','{"unit":"/ hour","lanes":"Lanes 1, 2, 5, 6, 7"}',true,300) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('team','cage','Team cage','Cage',60,60,0,0,0,0,false,false,false,'','','[]','{"unit":"/ hour","lanes":"Lanes 1, 2, 5, 6, 7"}',true,301) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('field','cage','Fielding area','Cage',75,60,0,0,0,0,false,false,false,'','','[]','{"unit":"/ hour","lanes":"Cages 3 and 4"}',true,302) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('prospect','cage_plan','Prospect','Cage',79,120,2,0,0,2,false,false,false,'One athlete · two sessions a month','One athlete · two sessions a month','["Two 1-hour cage rentals included","Household athletes only — not for team practices"]','{"period":"/ month","hourly":"$39.50 / included hour","bestFor":"One athlete · two sessions a month","savings":"About $21 vs two drop-in hours","perks":["Two 1-hour cage rentals included","Household athletes only — not for team practices"]}',true,400) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('all-star','cage_plan','All-Star','Cage',139,240,4,0,0,4,false,false,false,'The weekly trainer','The weekly trainer','["Four 1-hour cage rentals included","14-day priority booking","Household athletes only — not for team practices"]','{"period":"/ month","hourly":"$34.75 / included hour","bestFor":"The weekly trainer","savings":"About $61 vs four drop-in hours","perks":["Four 1-hour cage rentals included","14-day priority booking","Household athletes only — not for team practices"]}',true,401) on conflict (id) do nothing;
insert into club_services (id,kind,name,discipline,price,minutes,credits,remote,expires_days,hours,entry,group_session,requires_assessment,purpose,detail,includes_json,extra_json,active,sort_order) values ('elite-family','cage_plan','Elite Family','Cage',199,360,6,0,0,6,false,false,false,'Two household athletes','Two household athletes','["Six 1-hour cage rentals, shared","Two household athletes","Household use only — not for team practices"]','{"period":"/ month","hourly":"$33.17 / included hour","bestFor":"Two household athletes","savings":"Six hours to split across the household","perks":["Six 1-hour cage rentals, shared","Two household athletes","Household use only — not for team practices"]}',true,402) on conflict (id) do nothing;

-- The four explicit corrections approved in the audit request.
update club_services set price = case id when 'm1' then 239 when 'p2' then 385 when 'p3' then 740 when 's9' then 150 end where id in ('m1','p2','p3','s9');
update club_services set entry = true, requires_assessment = false where id in ('s1','s4','s9');
update club_services set requires_assessment = true where kind in ('lesson','package') and id not in ('s1','s4','s6','s9');

    INSERT INTO _migrations (name) VALUES ('0008_catalog.sql');
  END IF;
END
$netlify_apply$;
