import {useEffect,useState} from 'react';import {Link} from '@tanstack/react-router';
import {getMyCoach,saveMyCoach,saveMyAvailability} from '@/lib/coaching-api';
import {Button} from '@/components/ui/button';
const prompts=[['career','Baseball / softball career','Where have you played or coached? Include teams, roles, and dates you want to share.'],['approach','Coaching approach','What can a family expect in a lesson? How do you help an athlete improve?'],['ages','Athletes you work with','Describe age groups and experience levels.'],['achievements','Background & accomplishments','List qualifications or accomplishments you want families to know.'],['welcome','Message to new families','What should a player bring or prepare for the first session?']] as const;
export function CoachProfile(){const [data,setData]=useState<Awaited<ReturnType<typeof getMyCoach>>>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{void getMyCoach().then(setData).catch(e=>setError(e.message));},[]);
 return <section className="grid gap-4"><h2 className="text-3xl">Your coach profile</h2><p>Your own words appear on <Link to="/coaches" className="underline">Meet the coaches</Link> when you publish.</p>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{data?<>
 <form className="grid gap-4" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await saveMyCoach({data:{name:String(f.get('name')),specialties:String(f.get('specialties')).split(',').map(s=>s.trim()).filter(Boolean),career:String(f.get('career')),approach:String(f.get('approach')),ages:String(f.get('ages')),achievements:String(f.get('achievements')),welcome:String(f.get('welcome')),published:f.get('published')==='on'}});setNotice('Coach profile saved.');}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}}>
 <label>Display name<input name="name" required maxLength={120} defaultValue={data.profile?.name||data.coach.name}/></label><label>Specialties (comma separated)<input name="specialties" defaultValue={(data.profile?.specialties||data.coach.specialties).join(', ')}/></label>
 {prompts.map(([key,label,hint])=><label key={key}>{label}<span className="block text-sm text-muted">{hint}</span><textarea name={key} maxLength={key==='ages'?500:key==='welcome'?1000:2000} rows={3} defaultValue={data.profile?.[key]||''}/></label>)}
 <label className="flex gap-2"><input type="checkbox" name="published" defaultChecked={data.profile?.published}/>Publish this profile for parents and players</label><Button disabled={busy} type="submit">Save coach profile</Button></form>
 <h3 className="text-2xl">Weekly availability</h3><p>Current windows: {data.availability.map(w=>`${w.weekday} ${w.window}`).join('; ')||'None set'}. Saving replaces your weekly windows.</p>
 <form className="grid gap-3" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as const;setBusy(true);try{await saveMyAvailability({data:{windows:days.filter(d=>f.get(d)==='on').map(d=>({weekday:d,start:String(f.get(`${d}-start`)),end:String(f.get(`${d}-end`))}))}});setData(await getMyCoach());setNotice('Availability saved. Checkout uses these windows.');}catch(e){setError(e instanceof Error?e.message:'Availability did not save.');}finally{setBusy(false);}}}>
 {(['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as const).map(d=><fieldset key={d} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-3"><legend>{d}</legend><label><input name={d} type="checkbox"/>Available</label><label>Start<input name={`${d}-start`} type="time" defaultValue={['Sat','Sun'].includes(d)?'13:00':'16:00'}/></label><label>End<input name={`${d}-end`} type="time" defaultValue="20:00"/></label></fieldset>)}<Button type="submit" disabled={busy}>Save weekly availability</Button></form>
 </>:null}</section>;
}
