import {useEffect,useState} from 'react';
import {useDevelopment} from '@/lib/pd/context';
import {getDevelopmentProgress,saveTrack,saveTrainingDay,logTrainingItem,logSessionMetric} from '@/lib/coaching-api';
import {TRACKS,type dayInput} from '@/lib/coaching-contracts';
import type {z} from 'zod';
import {chicagoDate} from '@/lib/scheduling';
import {Button} from '@/components/ui/button';
const dates=()=>Array.from({length:30},(_,i)=>new Date(new Date(chicagoDate()+'T12:00:00Z').getTime()+i*86400000).toISOString().slice(0,10));
type Item=z.infer<typeof dayInput>['items'][number];
const newItem=():Item=>({id:crypto.randomUUID(),name:'',track:'Strength',sets:1,reps:'',instructions:'',videoUrl:''});
export function DevelopmentBoard(){
 const {data,viewer}=useDevelopment();const [id,setId]=useState(data.athletes[0]?.id||'');const [day,setDay]=useState(chicagoDate());
 const [progress,setProgress]=useState<Awaited<ReturnType<typeof getDevelopmentProgress>>>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [items,setItems]=useState<Item[]>([]);const coach=viewer?.role==='coach'||viewer?.role==='admin';
 const selected=progress?.days.find(d=>d.day===day);
 async function reload(){if(id)setProgress(await getDevelopmentProgress({data:{athleteId:id}}));}
 useEffect(()=>{let active=true;setProgress(undefined);if(id)void getDevelopmentProgress({data:{athleteId:id}}).then(p=>{if(active)setProgress(p);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);
 useEffect(()=>{setItems(selected?.items||[]);},[selected,day]);
 async function save(fn:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{await fn();await reload();setNotice('Saved to the athlete’s record.');}catch(e){setError(e instanceof Error?e.message:'Changes did not save.');}finally{setBusy(false);}}
 return <section className="grid min-w-0 gap-5"><h2 className="text-3xl">Development tracks & 30-day plan</h2><label>Athlete<select value={id} onChange={e=>setId(e.target.value)}><option value="">Choose athlete</option>{data.athletes.map(a=><option key={a.id} value={a.id}>{a.firstName} {a.lastName}</option>)}</select></label>{!id?<p>Add your athlete in the family account, then ask your coach to assign their plan.</p>:<>
 {error?<p role="alert" className="text-maroon">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 <div className="grid gap-3 sm:grid-cols-2">{TRACKS.map(track=>{const row=progress?.tracks.find(t=>t.track===track);return <article key={track} className="rounded-xl border p-4"><h3 className="text-xl">{track}</h3><p className="mt-2 text-2xl">{row?`OP-${row.level}`:'Not evaluated'}</p><div className="mt-3 flex gap-1" aria-label={row?`Level ${row.level} of 7`:'Seven levels; evaluation pending'}>{Array.from({length:7},(_,i)=><span key={i} className={`h-2 flex-1 rounded-full ${row&&i<row.level?'bg-maroon':'bg-line'}`}/>)}</div><p className="mt-3 text-sm">{row?.evidence||'Your coach records this track’s criteria and evaluation evidence before assigning a level.'}</p></article>;})}</div>
 {coach?<form className="grid gap-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>saveTrack({data:{athleteId:id,track:f.get('track') as typeof TRACKS[number],level:Number(f.get('level')),evidence:String(f.get('evidence'))}}));}}><h3 className="text-2xl">Update a development level</h3><label>Track<select name="track">{TRACKS.map(t=><option key={t}>{t}</option>)}</select></label><label>Level<select name="level">{[1,2,3,4,5,6,7].map(n=><option key={n} value={n}>OP-{n}</option>)}</select></label><label>Advancement criteria & observed evidence<textarea name="evidence" required minLength={10} maxLength={5000}/></label><Button type="submit" disabled={busy}>Save evaluated level</Button></form>:null}
 <div><h3 className="text-2xl">Next 30 days</h3><p className="mt-2">Choose a day to see assigned drills, lifting, and game adjustments. Empty days stay unassigned until your coach builds the work.</p><div className="mt-4 grid grid-cols-5 gap-2 sm:grid-cols-10">{dates().map(d=><button key={d} type="button" aria-pressed={day===d} onClick={()=>setDay(d)} className={`min-h-14 rounded-lg border p-2 ${day===d?'bg-navy text-white':'bg-paper text-ink'}`}><span className="block text-xs">{new Date(d+'T12:00Z').toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'})}</span>{Number(d.slice(-2))}<span className="block text-xs">{progress?.days.some(p=>p.day===d)?'Assigned':'—'}</span></button>)}</div></div>
 <article className="rounded-xl bg-paper-2 p-5"><h3 className="text-2xl">{day} · {selected?.focus||'No work assigned'}</h3>{selected?.game_notes?<p className="mt-2 font-semibold">Schedule / game adjustment: {selected.game_notes}</p>:null}
 {selected?.items.map(item=>{const log=progress?.logs.find(l=>l.day===day&&l.item_id===item.id);return <div key={item.id} className="mt-4 rounded-xl bg-paper p-4"><h4 className="text-xl">{item.name}</h4><p>{item.track} · {item.sets} sets · {item.reps}</p><details className="mt-2"><summary className="min-h-11 cursor-pointer py-2 font-semibold">How to do this</summary><p className="whitespace-pre-line">{item.instructions}</p>{item.videoUrl?<a href={item.videoUrl} className="inline-flex min-h-11 items-center underline">Watch the coach’s demonstration</a>:null}</details>
 <form className="mt-3 grid gap-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>logTrainingItem({data:{athleteId:id,day,itemId:item.id,completed:f.get('completed')==='on',reps:f.get('reps')?Number(f.get('reps')):undefined,weight:f.get('weight')?Number(f.get('weight')):undefined,rpe:f.get('rpe')?Number(f.get('rpe')):undefined,notes:String(f.get('notes')||'')}}));}}><div className="grid grid-cols-3 gap-2"><label>Reps<input type="number" name="reps" min={0} max={10000} defaultValue={log?.reps??''}/></label><label>Load (lb)<input type="number" name="weight" min={0} max={1500} step="0.5" defaultValue={log?.weight??''}/></label><label>Effort (1–10)<input type="number" name="rpe" min={1} max={10} defaultValue={log?.rpe??''}/></label></div><label>Session notes<textarea name="notes" maxLength={1000} defaultValue={log?.notes||''}/></label><label className="flex gap-2"><input type="checkbox" name="completed" defaultChecked={log?.completed}/>Completed</label><Button type="submit" disabled={busy}>Save workout log</Button></form></div>;})}
 </article>
 {coach?<form key={`${id}:${day}`} className="grid gap-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>saveTrainingDay({data:{athleteId:id,day,focus:String(f.get('focus')),gameNotes:String(f.get('gameNotes')||''),items}}));}}><h3 className="text-2xl">Plan {day}</h3><label>Specific improvement focus<input name="focus" required minLength={3} maxLength={300} defaultValue={selected?.focus||''}/></label><label>Game / schedule adjustment<textarea name="gameNotes" maxLength={1000} defaultValue={selected?.game_notes||''}/></label>
 {items.map((item,index)=><fieldset className="grid gap-2 rounded-lg border p-3" key={item.id}><legend>Drill or lift {index+1}</legend><label>Name<input required value={item.name} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/></label><label>Track<select value={item.track} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,track:e.target.value as Item['track']}:x))}>{[...TRACKS,'Strength','Recovery'].map(t=><option key={t}>{t}</option>)}</select></label><label>Sets<input type="number" required min={1} max={100} value={item.sets} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,sets:Number(e.target.value)}:x))}/></label><label>Reps / time / distance<input required maxLength={80} value={item.reps} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,reps:e.target.value}:x))}/></label><label>Step-by-step instructions<textarea required minLength={5} maxLength={3000} value={item.instructions} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,instructions:e.target.value}:x))}/></label><label>Demonstration URL (optional)<input type="url" value={item.videoUrl} onChange={e=>setItems(old=>old.map((x,i)=>i===index?{...x,videoUrl:e.target.value}:x))}/></label><Button type="button" variant="outlineDark" onClick={()=>setItems(old=>old.filter((_,i)=>i!==index))}>Remove this item</Button></fieldset>)}
 <Button type="button" variant="outlineDark" onClick={()=>setItems(old=>[...old,newItem()])} disabled={items.length>=20}>Add drill or lift</Button><Button type="submit" disabled={busy}>Publish this training day</Button></form>:null}
 <h3 className="text-2xl">Session performance tracker</h3><p>Log successful executions and total attempts against a specific drill target. Percentages describe this session, not an age-based ranking.</p>
 {progress?.metrics.map(m=><p key={m.id} className="rounded-lg border p-3">{m.day} · {m.track} · {m.successes}/{m.attempts} ({Math.round(m.successes/m.attempts*100)}%) · {m.verified?'Coach recorded':'Family log'}<span className="block">{m.notes}</span></p>)}
 <form className="grid gap-3" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>logSessionMetric({data:{id:crypto.randomUUID(),athleteId:id,track:f.get('track') as typeof TRACKS[number],day:String(f.get('day')),successes:Number(f.get('successes')),attempts:Number(f.get('attempts')),notes:String(f.get('notes'))}}));}}><label>Track<select name="track">{TRACKS.map(t=><option key={t}>{t}</option>)}</select></label><label>Session date<input name="day" type="date" required max={chicagoDate()} defaultValue={chicagoDate()}/></label><div className="grid grid-cols-2 gap-3"><label>Successful reps<input name="successes" required type="number" min={0} max={10000}/></label><label>Total attempts<input name="attempts" required type="number" min={1} max={10000}/></label></div><label>Drill, target & observations<textarea name="notes" minLength={3} maxLength={2000} required/></label><Button type="submit" disabled={busy}>Save session results</Button></form>
 </>}</section>;
}
