import {useEffect,useState} from 'react';
import {getOfficeRequests,closeOfficeRequest} from '@/lib/portal-api';
import {getTeamsClub,reviewTeamInquiry} from '@/lib/teams/store';
import {Button} from '@/components/ui/button';
export function OfficeRequests(){
 const [rows,setRows]=useState<Awaited<ReturnType<typeof getOfficeRequests>>>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [teams,setTeams]=useState<{id:string;name:string}[]>([]),[notice,setNotice]=useState('');
 async function load(){const [requests,club]=await Promise.all([getOfficeRequests(),getTeamsClub()]);setRows(requests);setTeams(club.ok?club.club.teams.map(t=>({id:t.id,name:t.name})):[]);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 return <section className="my-6 grid gap-3"><h2 className="text-3xl">Registrations & requests</h2>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{!rows.length&&!error?<p>No submitted requests.</p>:null}{rows.map(r=><article key={r.id} className="rounded-xl border p-4"><h3 className="text-xl">{r.kind} · {r.status}</h3><p>{new Date(r.created_at).toLocaleString('en-US',{timeZone:'America/Chicago'})}</p><dl>{Object.entries(r.payload).filter(([key])=>key!=='requestId').map(([key,value])=><div key={key} className="mt-1 break-words"><dt className="font-semibold">{key}</dt><dd>{typeof value==='string'||typeof value==='number'?String(value):JSON.stringify(value)}</dd></div>)}</dl>{['tryout','team-inquiry'].includes(r.kind)&&!r.payload.rosterPlayerId?<form className="mt-3 grid gap-3" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const saved=await reviewTeamInquiry({data:{id:r.id,teamId:String(form.get('team')),stage:form.get('stage') as 'registered'|'evaluated'|'offer'|'accepted'|'waitlist'}});setNotice(saved.message);await load();}catch(e){setError(e instanceof Error?e.message:'Could not update registration.');}finally{setBusy(false);}}}><label>Team<select required name="team" defaultValue=""><option value="">Choose a team</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Registration stage<select name="stage" defaultValue="registered"><option value="registered">Registered</option><option value="evaluated">Evaluated</option><option value="offer">Offer</option><option value="waitlist">Waitlist</option><option value="accepted">Accepted — add to roster and create guardian invitation</option></select></label><Button disabled={busy}>Save registration stage</Button></form>:null}{r.status==='open'&&!['tryout','team-inquiry','membership-pause','refund-review'].includes(r.kind)?<Button className="mt-3" variant="outlineDark" disabled={busy} onClick={async()=>{setBusy(true);try{await closeOfficeRequest({data:{id:r.id}});await load();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}}>Mark request resolved</Button>:null}{['membership-pause','refund-review'].includes(r.kind)?<p className="mt-3">Billing review required. This request does not change a subscription or issue a refund. Confirm the policy and provider outcome before closing it.</p>:null}</article>)}</section>;
}
