import {useEffect,useState} from 'react';
import {getOfficeOperations,getEarnings,settleEarning,setServiceResources,saveBookingParticipants} from '@/lib/commerce/operations-api';
import {checkInBooking} from '@/lib/commerce/portal-api';
import {BOOKABLE_LANES} from '@/lib/club';
import {formatMoney} from '@/lib/pricing';
import {Button} from '@/components/ui/button';
export function Participants({id,count,athletes,onSaved}:{id:string;count:number;athletes:{id:string;name:string}[];onSaved:()=>Promise<void>}) {
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <details className="mt-3"><summary className="min-h-11 cursor-pointer">Confirm {count} participating athlete{count===1?'':'s'}</summary><form className="grid gap-2" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await saveBookingParticipants({data:{id,athleteIds:form.getAll('athlete').map(String)}});await onSaved();}catch(e){setError(e instanceof Error?e.message:'Participants did not save.');}finally{setBusy(false);}}}>
 {athletes.map(a=><label key={a.id} className="flex min-h-11 items-center gap-3"><input type="checkbox" name="athlete" value={a.id}/>{a.name}</label>)}<p>Add missing household athletes in Bookings & billing, then sign their annual waivers.</p><Button disabled={busy}>Save participants</Button>{error?<p role="alert">{error}</p>:null}</form></details>;
}
export function ContractorEarnings() {
 const [data,setData]=useState<Awaited<ReturnType<typeof getEarnings>>>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await getEarnings());}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 return <section className="my-6 grid gap-3"><h3 className="text-2xl">1099 contractor earnings</h3><p>Completed paid sessions and the configured coach share. Record an external payment only after it has been paid.</p>{error?<p role="alert">{error}</p>:null}{data?.rows.length===0?<p>No earnings recorded yet.</p>:null}
 {data?.rows.map(r=><article key={r.booking_id} className="rounded-xl border p-4"><p>{formatMoney(r.amount_cents)} · {r.status} · {r.split_pct}% of {formatMoney(r.gross_cents)}</p><p>Booking {r.booking_id}</p>{r.transfer_id?<p>Payment reference: {r.transfer_id}</p>:null}{data.canSettle&&r.status==='payable'?<form className="mt-3 grid gap-2" onSubmit={async e=>{e.preventDefault();const reference=String(new FormData(e.currentTarget).get('reference'));setBusy(true);setError('');try{await settleEarning({data:{id:r.booking_id,reference}});await load();}catch(e){setError(e instanceof Error?e.message:'Payment record did not save.');}finally{setBusy(false);}}}><label>Unique payment reference<input name="reference" required minLength={4} maxLength={150}/></label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" required/>I confirm this payment was already sent to this contractor.</label><Button disabled={busy}>Record paid settlement</Button></form>:null}</article>)}</section>;
}
export function OfficeOperations() {
 const [data,setData]=useState<Awaited<ReturnType<typeof getOfficeOperations>>>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setData(await getOfficeOperations());}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function action(work:()=>Promise<unknown>){setBusy(true);setError('');try{await work();await load();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 return <section className="my-6 grid gap-4"><h2 className="text-3xl">Bookings, waivers & records</h2>{error?<p role="alert">{error}</p>:null}
 <h3 className="text-2xl">Upcoming visits</h3>{data?.bookings.length===0?<p>No confirmed visits in the next two weeks.</p>:null}{data?.bookings.map(b=><article key={b.id} className="rounded-xl border p-4"><p>{new Date(b.starts_at).toLocaleString('en-US',{timeZone:'America/Chicago'})} · {b.product_id}</p><p>{b.participant_names||'Participants not confirmed'} · expected {b.participant_count}</p><p>{b.missing_waivers?'Current waivers needed':'Listed participants have current waivers'}</p><Button disabled={busy||!!b.checked_in_at} onClick={()=>void action(()=>checkInBooking({data:{id:b.id}}))}>{b.checked_in_at?'Checked in':'Check in — verify all waivers'}</Button></article>)}
 <details><summary className="min-h-11 cursor-pointer text-xl">Lesson facility spaces</summary><p>Assign the lane or lanes required for each lesson. A coach, athlete and these spaces are reserved together. New bookings stay closed for services without a space assignment.</p>{data?.resources.map(r=><form key={r.service_id} className="mt-4 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();const laneIds=new FormData(e.currentTarget).getAll('lane').map(String);void action(()=>setServiceResources({data:{id:r.service_id,laneIds}}));}}><fieldset><legend className="font-semibold">{r.name}</legend>{BOOKABLE_LANES.map(l=><label key={l.id} className="flex min-h-11 items-center gap-3"><input name="lane" type="checkbox" value={l.id} defaultChecked={r.lane_ids?.includes(l.id)}/>{l.name}</label>)}</fieldset><Button disabled={busy}>Save facility requirement</Button></form>)}</details>
 <details><summary className="min-h-11 cursor-pointer text-xl">Reconciliation overview</summary>{data?<><p>Legacy reservations: {data.counts.legacy_reservations}; legacy assessment flags: {data.counts.legacy_assessments}. Authoritative confirmed/completed bookings: {data.counts.confirmed_bookings}; coach-verified assessments: {data.counts.verified_assessments}. Paid order total: {formatMoney(data.counts.paid_cents)}; payments needing review: {data.counts.open_review}.</p><p>These counts identify records to review; they do not establish matching balances. Verify legacy receipts, assessments and reservations before recording opening balances. No legacy payment or completion flag is converted automatically.</p></>:null}</details>
 <details><summary className="min-h-11 cursor-pointer text-xl">Recent administrative audit events</summary><ul>{data?.events.map(e=><li className="mt-2 break-words" key={e.id}>{new Date(e.created_at).toLocaleString()} · {e.action} · {e.target_table} · {e.target_id} · actor {e.actor_id}</li>)}</ul></details>
 <ContractorEarnings/>
 </section>;
}
