import test from 'node:test';import assert from 'node:assert/strict';import {mkdir,writeFile,rm} from 'node:fs/promises';import {resolve} from 'node:path';import {pathToFileURL} from 'node:url';import {build} from 'esbuild';import {JSDOM} from 'jsdom';
test('team activity editor saves per-game data; family view is read-only with group chat',async()=>{
 const dom=new JSDOM('<div id="root"></div>',{url:'https://fixture.invalid/coach'});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const {act,createElement}=await import('react'),{createRoot}=await import('react-dom/client');
 const activity={teamId:'team',id:'11111111-1111-4111-8111-111111111111',revision:1,kind:'game',title:'Opponent',date:'2027-03-01',startTime:'18:00',endTime:'20:00',location:'Home field',status:'final',ourRuns:4,oppRuns:2,stats:[{playerId:'player',values:{ab:3,h:1,r:1,hr:0,rbi:0,sb:0,bb:0,so:0}}]};
 const fixture={data:{manage:true,teamName:'Prospects',record:{w:1,l:0,t:0},players:[{id:'player',name:'Player One',number:'1',stats:{ab:3,h:1}}],activities:[activity],messages:[{id:'message',author:'Parent One',body:'Team-only update',at:'2026-10-10T12:00:00Z'}]},saved:[]};globalThis.__activityFixture=fixture;
 const out=resolve('artifacts/team-activity-render.mjs');await mkdir('artifacts',{recursive:true});const result=await build({entryPoints:['src/components/teams/team-activities.tsx'],bundle:true,platform:'node',format:'esm',write:false,external:['react','react/*','react-dom','react-dom/*'],plugins:[{name:'activity-fixture',setup(b){b.onResolve({filter:/^@\/lib\/teams\/activity-api$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:`export const getTeamActivities=async()=>globalThis.__activityFixture.data;export const changeTeamActivity=async({data})=>{globalThis.__activityFixture.saved.push(data);return {id:data.id};};export const sendTeamChat=async()=>({ok:true});`,loader:'js'}));}}]});await writeFile(out,result.outputFiles[0].text);const {TeamActivities}=await import(pathToFileURL(out).href);const host=document.getElementById('root');let root=createRoot(host);const button=name=>[...host.querySelectorAll('button')].find(b=>b.textContent===name);
 try{await act(async()=>root.render(createElement(TeamActivities,{teamId:'team'})));assert.match(host.textContent,/4–2 · Win/);assert.match(host.textContent,/Parent One/);await act(async()=>button('Edit activity').click());assert.match(host.textContent,/Player stats for this game/);await act(async()=>host.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.deepEqual(fixture.saved[0],activity);assert.match(host.textContent,/Schedule and stats saved/);
 await act(async()=>root.unmount());fixture.data.manage=false;root=createRoot(host);await act(async()=>root.render(createElement(TeamActivities,{teamId:'team'})));assert.equal(button('Edit activity'),undefined);assert.equal(button('Add game, tournament or practice'),undefined);assert.ok(button('Post to team'));assert.match(host.textContent,/Player stats/);
 }finally{await act(async()=>root.unmount());dom.window.close();delete globalThis.__activityFixture;await rm(out,{force:true});}
});
