/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BookRouteImport } from './routes/book'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TryoutsRouteImport } from './routes/tryouts'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as GoDestRouteImport } from './routes/go.$dest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutsRoute = TryoutsRouteImport.update({
  id: '/tryouts',
  path: '/tryouts',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const GoDestRoute = GoDestRouteImport.update({
  id: '/go/$dest',
  path: '/go/$dest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/go/$dest': typeof GoDestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/go/$dest': typeof GoDestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/go/$dest': typeof GoDestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/contact'
    | '/facility'
    | '/family'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/training'
    | '/tryouts'
    | '/visits'
    | '/waiver'
    | '/go/$dest'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/contact'
    | '/facility'
    | '/family'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/training'
    | '/tryouts'
    | '/visits'
    | '/waiver'
    | '/go/$dest'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/contact'
    | '/facility'
    | '/family'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/training'
    | '/tryouts'
    | '/visits'
    | '/waiver'
    | '/go/$dest'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookRoute: typeof BookRoute
  CoachRoute: typeof CoachRoute
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  FamilyRoute: typeof FamilyRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MembershipsRoute: typeof MembershipsRoute
  MoreRoute: typeof MoreRoute
  OfficeRoute: typeof OfficeRoute
  PaidRoute: typeof PaidRoute
  ParentsRoute: typeof ParentsRoute
  PayRoute: typeof PayRoute
  PrivacyRoute: typeof PrivacyRoute
  RecruitingRoute: typeof RecruitingRoute
  TeamsRoute: typeof TeamsRoute
  TrainingRoute: typeof TrainingRoute
  TryoutsRoute: typeof TryoutsRoute
  VisitsRoute: typeof VisitsRoute
  WaiverRoute: typeof WaiverRoute
  GoDestRoute: typeof GoDestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryouts': {
      id: '/tryouts'
      path: '/tryouts'
      fullPath: '/tryouts'
      preLoaderRoute: typeof TryoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$dest': {
      id: '/go/$dest'
      path: '/go/$dest'
      fullPath: '/go/$dest'
      preLoaderRoute: typeof GoDestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookRoute: BookRoute,
  CoachRoute: CoachRoute,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  FamilyRoute: FamilyRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MembershipsRoute: MembershipsRoute,
  MoreRoute: MoreRoute,
  OfficeRoute: OfficeRoute,
  PaidRoute: PaidRoute,
  ParentsRoute: ParentsRoute,
  PayRoute: PayRoute,
  PrivacyRoute: PrivacyRoute,
  RecruitingRoute: RecruitingRoute,
  TeamsRoute: TeamsRoute,
  TrainingRoute: TrainingRoute,
  TryoutsRoute: TryoutsRoute,
  VisitsRoute: VisitsRoute,
  WaiverRoute: WaiverRoute,
  GoDestRoute: GoDestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
