/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BookRouteImport } from './routes/book'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecruitingRouteImport } from './routes/recruiting'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TryoutsRouteImport } from './routes/tryouts'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as ApiSiteAlertsRouteImport } from './routes/api/site-alerts'
import { Route as FundraisingIndexRouteImport } from './routes/fundraising.index'
import { Route as FundraisingExampleRouteImport } from './routes/fundraising.example'
import { Route as FundraisingMyRouteImport } from './routes/fundraising.my'
import { Route as FundraisingOfficeRouteImport } from './routes/fundraising.office'
import { Route as FundraisingThankYouRouteImport } from './routes/fundraising.thank-you'
import { Route as GoDestRouteImport } from './routes/go.$dest'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFundraisingCheckoutRouteImport } from './routes/api/fundraising/checkout'
import { Route as ApiFundraisingDashboardRouteImport } from './routes/api/fundraising/dashboard'
import { Route as ApiFundraisingExportRouteImport } from './routes/api/fundraising/export'
import { Route as ApiFundraisingPlayersRouteImport } from './routes/api/fundraising/players'
import { Route as ApiFundraisingReceiptRouteImport } from './routes/api/fundraising/receipt'
import { Route as ApiFundraisingReconcileRouteImport } from './routes/api/fundraising/reconcile'
import { Route as ApiSquareReconcileRouteImport } from './routes/api/square/reconcile'
import { Route as ApiSquareWebhookRouteImport } from './routes/api/square/webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as FundraisingPIdRouteImport } from './routes/fundraising.p.$id'
import { Route as ApiFundraisingPlayersIdRouteImport } from './routes/api/fundraising/players.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitingRoute = RecruitingRouteImport.update({
  id: '/recruiting',
  path: '/recruiting',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TryoutsRoute = TryoutsRouteImport.update({
  id: '/tryouts',
  path: '/tryouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteAlertsRoute = ApiSiteAlertsRouteImport.update({
  id: '/api/site-alerts',
  path: '/api/site-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingIndexRoute = FundraisingIndexRouteImport.update({
  id: '/fundraising/',
  path: '/fundraising/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingExampleRoute = FundraisingExampleRouteImport.update({
  id: '/fundraising/example',
  path: '/fundraising/example',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingMyRoute = FundraisingMyRouteImport.update({
  id: '/fundraising/my',
  path: '/fundraising/my',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingOfficeRoute = FundraisingOfficeRouteImport.update({
  id: '/fundraising/office',
  path: '/fundraising/office',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingThankYouRoute = FundraisingThankYouRouteImport.update({
  id: '/fundraising/thank-you',
  path: '/fundraising/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const GoDestRoute = GoDestRouteImport.update({
  id: '/go/$dest',
  path: '/go/$dest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingCheckoutRoute = ApiFundraisingCheckoutRouteImport.update({
  id: '/api/fundraising/checkout',
  path: '/api/fundraising/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingDashboardRoute = ApiFundraisingDashboardRouteImport.update({
  id: '/api/fundraising/dashboard',
  path: '/api/fundraising/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingExportRoute = ApiFundraisingExportRouteImport.update({
  id: '/api/fundraising/export',
  path: '/api/fundraising/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingPlayersRoute = ApiFundraisingPlayersRouteImport.update({
  id: '/api/fundraising/players',
  path: '/api/fundraising/players',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingReceiptRoute = ApiFundraisingReceiptRouteImport.update({
  id: '/api/fundraising/receipt',
  path: '/api/fundraising/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingReconcileRoute = ApiFundraisingReconcileRouteImport.update({
  id: '/api/fundraising/reconcile',
  path: '/api/fundraising/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareReconcileRoute = ApiSquareReconcileRouteImport.update({
  id: '/api/square/reconcile',
  path: '/api/square/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSquareWebhookRoute = ApiSquareWebhookRouteImport.update({
  id: '/api/square/webhook',
  path: '/api/square/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const FundraisingPIdRoute = FundraisingPIdRouteImport.update({
  id: '/fundraising/p/$id',
  path: '/fundraising/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFundraisingPlayersIdRoute = ApiFundraisingPlayersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiFundraisingPlayersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/two-factor': typeof TwoFactorRoute
  '/visit': typeof VisitRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/api/site-alerts': typeof ApiSiteAlertsRoute
  '/fundraising/example': typeof FundraisingExampleRoute
  '/fundraising/my': typeof FundraisingMyRoute
  '/fundraising/office': typeof FundraisingOfficeRoute
  '/fundraising/thank-you': typeof FundraisingThankYouRoute
  '/go/$dest': typeof GoDestRoute
  '/fundraising/': typeof FundraisingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fundraising/checkout': typeof ApiFundraisingCheckoutRoute
  '/api/fundraising/dashboard': typeof ApiFundraisingDashboardRoute
  '/api/fundraising/export': typeof ApiFundraisingExportRoute
  '/api/fundraising/players': typeof ApiFundraisingPlayersRouteWithChildren
  '/api/fundraising/receipt': typeof ApiFundraisingReceiptRoute
  '/api/fundraising/reconcile': typeof ApiFundraisingReconcileRoute
  '/api/square/reconcile': typeof ApiSquareReconcileRoute
  '/api/square/webhook': typeof ApiSquareWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/fundraising/p/$id': typeof FundraisingPIdRoute
  '/api/fundraising/players/$id': typeof ApiFundraisingPlayersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/two-factor': typeof TwoFactorRoute
  '/visit': typeof VisitRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/api/site-alerts': typeof ApiSiteAlertsRoute
  '/fundraising/example': typeof FundraisingExampleRoute
  '/fundraising/my': typeof FundraisingMyRoute
  '/fundraising/office': typeof FundraisingOfficeRoute
  '/fundraising/thank-you': typeof FundraisingThankYouRoute
  '/go/$dest': typeof GoDestRoute
  '/fundraising': typeof FundraisingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fundraising/checkout': typeof ApiFundraisingCheckoutRoute
  '/api/fundraising/dashboard': typeof ApiFundraisingDashboardRoute
  '/api/fundraising/export': typeof ApiFundraisingExportRoute
  '/api/fundraising/players': typeof ApiFundraisingPlayersRouteWithChildren
  '/api/fundraising/receipt': typeof ApiFundraisingReceiptRoute
  '/api/fundraising/reconcile': typeof ApiFundraisingReconcileRoute
  '/api/square/reconcile': typeof ApiSquareReconcileRoute
  '/api/square/webhook': typeof ApiSquareWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/fundraising/p/$id': typeof FundraisingPIdRoute
  '/api/fundraising/players/$id': typeof ApiFundraisingPlayersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/book': typeof BookRoute
  '/coach': typeof CoachRoute
  '/coaches': typeof CoachesRoute
  '/contact': typeof ContactRoute
  '/facility': typeof FacilityRoute
  '/family': typeof FamilyRoute
  '/invitations': typeof InvitationsRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/memberships': typeof MembershipsRoute
  '/more': typeof MoreRoute
  '/office': typeof OfficeRoute
  '/paid': typeof PaidRoute
  '/parents': typeof ParentsRoute
  '/pay': typeof PayRoute
  '/privacy': typeof PrivacyRoute
  '/recruiting': typeof RecruitingRoute
  '/teams': typeof TeamsRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/tryouts': typeof TryoutsRoute
  '/two-factor': typeof TwoFactorRoute
  '/visit': typeof VisitRoute
  '/visits': typeof VisitsRoute
  '/waiver': typeof WaiverRoute
  '/api/site-alerts': typeof ApiSiteAlertsRoute
  '/fundraising/example': typeof FundraisingExampleRoute
  '/fundraising/my': typeof FundraisingMyRoute
  '/fundraising/office': typeof FundraisingOfficeRoute
  '/fundraising/thank-you': typeof FundraisingThankYouRoute
  '/go/$dest': typeof GoDestRoute
  '/fundraising/': typeof FundraisingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/fundraising/checkout': typeof ApiFundraisingCheckoutRoute
  '/api/fundraising/dashboard': typeof ApiFundraisingDashboardRoute
  '/api/fundraising/export': typeof ApiFundraisingExportRoute
  '/api/fundraising/players': typeof ApiFundraisingPlayersRouteWithChildren
  '/api/fundraising/receipt': typeof ApiFundraisingReceiptRoute
  '/api/fundraising/reconcile': typeof ApiFundraisingReconcileRoute
  '/api/square/reconcile': typeof ApiSquareReconcileRoute
  '/api/square/webhook': typeof ApiSquareWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/fundraising/p/$id': typeof FundraisingPIdRoute
  '/api/fundraising/players/$id': typeof ApiFundraisingPlayersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/coaches'
    | '/contact'
    | '/facility'
    | '/family'
    | '/invitations'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/terms'
    | '/training'
    | '/tryouts'
    | '/two-factor'
    | '/visit'
    | '/visits'
    | '/waiver'
    | '/api/site-alerts'
    | '/fundraising/example'
    | '/fundraising/my'
    | '/fundraising/office'
    | '/fundraising/thank-you'
    | '/go/$dest'
    | '/fundraising/'
    | '/api/auth/$'
    | '/api/fundraising/checkout'
    | '/api/fundraising/dashboard'
    | '/api/fundraising/export'
    | '/api/fundraising/players'
    | '/api/fundraising/receipt'
    | '/api/fundraising/reconcile'
    | '/api/square/reconcile'
    | '/api/square/webhook'
    | '/api/stripe/webhook'
    | '/fundraising/p/$id'
    | '/api/fundraising/players/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/coaches'
    | '/contact'
    | '/facility'
    | '/family'
    | '/invitations'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/terms'
    | '/training'
    | '/tryouts'
    | '/two-factor'
    | '/visit'
    | '/visits'
    | '/waiver'
    | '/api/site-alerts'
    | '/fundraising/example'
    | '/fundraising/my'
    | '/fundraising/office'
    | '/fundraising/thank-you'
    | '/go/$dest'
    | '/fundraising'
    | '/api/auth/$'
    | '/api/fundraising/checkout'
    | '/api/fundraising/dashboard'
    | '/api/fundraising/export'
    | '/api/fundraising/players'
    | '/api/fundraising/receipt'
    | '/api/fundraising/reconcile'
    | '/api/square/reconcile'
    | '/api/square/webhook'
    | '/api/stripe/webhook'
    | '/fundraising/p/$id'
    | '/api/fundraising/players/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/book'
    | '/coach'
    | '/coaches'
    | '/contact'
    | '/facility'
    | '/family'
    | '/invitations'
    | '/login'
    | '/members'
    | '/memberships'
    | '/more'
    | '/office'
    | '/paid'
    | '/parents'
    | '/pay'
    | '/privacy'
    | '/recruiting'
    | '/teams'
    | '/terms'
    | '/training'
    | '/tryouts'
    | '/two-factor'
    | '/visit'
    | '/visits'
    | '/waiver'
    | '/api/site-alerts'
    | '/fundraising/example'
    | '/fundraising/my'
    | '/fundraising/office'
    | '/fundraising/thank-you'
    | '/go/$dest'
    | '/fundraising/'
    | '/api/auth/$'
    | '/api/fundraising/checkout'
    | '/api/fundraising/dashboard'
    | '/api/fundraising/export'
    | '/api/fundraising/players'
    | '/api/fundraising/receipt'
    | '/api/fundraising/reconcile'
    | '/api/square/reconcile'
    | '/api/square/webhook'
    | '/api/stripe/webhook'
    | '/fundraising/p/$id'
    | '/api/fundraising/players/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookRoute: typeof BookRoute
  CoachRoute: typeof CoachRoute
  CoachesRoute: typeof CoachesRoute
  ContactRoute: typeof ContactRoute
  FacilityRoute: typeof FacilityRoute
  FamilyRoute: typeof FamilyRoute
  InvitationsRoute: typeof InvitationsRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MembershipsRoute: typeof MembershipsRoute
  MoreRoute: typeof MoreRoute
  OfficeRoute: typeof OfficeRoute
  PaidRoute: typeof PaidRoute
  ParentsRoute: typeof ParentsRoute
  PayRoute: typeof PayRoute
  PrivacyRoute: typeof PrivacyRoute
  RecruitingRoute: typeof RecruitingRoute
  TeamsRoute: typeof TeamsRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRoute
  TryoutsRoute: typeof TryoutsRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VisitRoute: typeof VisitRoute
  VisitsRoute: typeof VisitsRoute
  WaiverRoute: typeof WaiverRoute
  ApiSiteAlertsRoute: typeof ApiSiteAlertsRoute
  FundraisingExampleRoute: typeof FundraisingExampleRoute
  FundraisingMyRoute: typeof FundraisingMyRoute
  FundraisingOfficeRoute: typeof FundraisingOfficeRoute
  FundraisingThankYouRoute: typeof FundraisingThankYouRoute
  GoDestRoute: typeof GoDestRoute
  FundraisingIndexRoute: typeof FundraisingIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFundraisingCheckoutRoute: typeof ApiFundraisingCheckoutRoute
  ApiFundraisingDashboardRoute: typeof ApiFundraisingDashboardRoute
  ApiFundraisingExportRoute: typeof ApiFundraisingExportRoute
  ApiFundraisingPlayersRoute: typeof ApiFundraisingPlayersRouteWithChildren
  ApiFundraisingReceiptRoute: typeof ApiFundraisingReceiptRoute
  ApiFundraisingReconcileRoute: typeof ApiFundraisingReconcileRoute
  ApiSquareReconcileRoute: typeof ApiSquareReconcileRoute
  ApiSquareWebhookRoute: typeof ApiSquareWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  FundraisingPIdRoute: typeof FundraisingPIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiting': {
      id: '/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof RecruitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tryouts': {
      id: '/tryouts'
      path: '/tryouts'
      fullPath: '/tryouts'
      preLoaderRoute: typeof TryoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-alerts': {
      id: '/api/site-alerts'
      path: '/api/site-alerts'
      fullPath: '/api/site-alerts'
      preLoaderRoute: typeof ApiSiteAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/': {
      id: '/fundraising/'
      path: '/fundraising'
      fullPath: '/fundraising/'
      preLoaderRoute: typeof FundraisingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/example': {
      id: '/fundraising/example'
      path: '/fundraising/example'
      fullPath: '/fundraising/example'
      preLoaderRoute: typeof FundraisingExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/my': {
      id: '/fundraising/my'
      path: '/fundraising/my'
      fullPath: '/fundraising/my'
      preLoaderRoute: typeof FundraisingMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/office': {
      id: '/fundraising/office'
      path: '/fundraising/office'
      fullPath: '/fundraising/office'
      preLoaderRoute: typeof FundraisingOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/thank-you': {
      id: '/fundraising/thank-you'
      path: '/fundraising/thank-you'
      fullPath: '/fundraising/thank-you'
      preLoaderRoute: typeof FundraisingThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$dest': {
      id: '/go/$dest'
      path: '/go/$dest'
      fullPath: '/go/$dest'
      preLoaderRoute: typeof GoDestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/checkout': {
      id: '/api/fundraising/checkout'
      path: '/api/fundraising/checkout'
      fullPath: '/api/fundraising/checkout'
      preLoaderRoute: typeof ApiFundraisingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/dashboard': {
      id: '/api/fundraising/dashboard'
      path: '/api/fundraising/dashboard'
      fullPath: '/api/fundraising/dashboard'
      preLoaderRoute: typeof ApiFundraisingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/export': {
      id: '/api/fundraising/export'
      path: '/api/fundraising/export'
      fullPath: '/api/fundraising/export'
      preLoaderRoute: typeof ApiFundraisingExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/players': {
      id: '/api/fundraising/players'
      path: '/api/fundraising/players'
      fullPath: '/api/fundraising/players'
      preLoaderRoute: typeof ApiFundraisingPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/receipt': {
      id: '/api/fundraising/receipt'
      path: '/api/fundraising/receipt'
      fullPath: '/api/fundraising/receipt'
      preLoaderRoute: typeof ApiFundraisingReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/reconcile': {
      id: '/api/fundraising/reconcile'
      path: '/api/fundraising/reconcile'
      fullPath: '/api/fundraising/reconcile'
      preLoaderRoute: typeof ApiFundraisingReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/reconcile': {
      id: '/api/square/reconcile'
      path: '/api/square/reconcile'
      fullPath: '/api/square/reconcile'
      preLoaderRoute: typeof ApiSquareReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/square/webhook': {
      id: '/api/square/webhook'
      path: '/api/square/webhook'
      fullPath: '/api/square/webhook'
      preLoaderRoute: typeof ApiSquareWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundraising/p/$id': {
      id: '/fundraising/p/$id'
      path: '/fundraising/p/$id'
      fullPath: '/fundraising/p/$id'
      preLoaderRoute: typeof FundraisingPIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fundraising/players/$id': {
      id: '/api/fundraising/players/$id'
      path: '/$id'
      fullPath: '/api/fundraising/players/$id'
      preLoaderRoute: typeof ApiFundraisingPlayersIdRouteImport
      parentRoute: typeof ApiFundraisingPlayersRoute
    }
  }
}

interface ApiFundraisingPlayersRouteChildren {
  ApiFundraisingPlayersIdRoute: typeof ApiFundraisingPlayersIdRoute
}

const ApiFundraisingPlayersRouteChildren: ApiFundraisingPlayersRouteChildren = {
  ApiFundraisingPlayersIdRoute: ApiFundraisingPlayersIdRoute,
}

const ApiFundraisingPlayersRouteWithChildren =
  ApiFundraisingPlayersRoute._addFileChildren(
    ApiFundraisingPlayersRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookRoute: BookRoute,
  CoachRoute: CoachRoute,
  CoachesRoute: CoachesRoute,
  ContactRoute: ContactRoute,
  FacilityRoute: FacilityRoute,
  FamilyRoute: FamilyRoute,
  InvitationsRoute: InvitationsRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MembershipsRoute: MembershipsRoute,
  MoreRoute: MoreRoute,
  OfficeRoute: OfficeRoute,
  PaidRoute: PaidRoute,
  ParentsRoute: ParentsRoute,
  PayRoute: PayRoute,
  PrivacyRoute: PrivacyRoute,
  RecruitingRoute: RecruitingRoute,
  TeamsRoute: TeamsRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRoute,
  TryoutsRoute: TryoutsRoute,
  TwoFactorRoute: TwoFactorRoute,
  VisitRoute: VisitRoute,
  VisitsRoute: VisitsRoute,
  WaiverRoute: WaiverRoute,
  ApiSiteAlertsRoute: ApiSiteAlertsRoute,
  FundraisingExampleRoute: FundraisingExampleRoute,
  FundraisingMyRoute: FundraisingMyRoute,
  FundraisingOfficeRoute: FundraisingOfficeRoute,
  FundraisingThankYouRoute: FundraisingThankYouRoute,
  GoDestRoute: GoDestRoute,
  FundraisingIndexRoute: FundraisingIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFundraisingCheckoutRoute: ApiFundraisingCheckoutRoute,
  ApiFundraisingDashboardRoute: ApiFundraisingDashboardRoute,
  ApiFundraisingExportRoute: ApiFundraisingExportRoute,
  ApiFundraisingPlayersRoute: ApiFundraisingPlayersRouteWithChildren,
  ApiFundraisingReceiptRoute: ApiFundraisingReceiptRoute,
  ApiFundraisingReconcileRoute: ApiFundraisingReconcileRoute,
  ApiSquareReconcileRoute: ApiSquareReconcileRoute,
  ApiSquareWebhookRoute: ApiSquareWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  FundraisingPIdRoute: FundraisingPIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
